name: warranty_keeper
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  image_picker: ^0.8.4+5
  flutter_cupertino_datetime_picker: ^3.0.0
  freezed_annotation: ^1.1.0
  path: ^1.8.1
  path_provider: ^2.0.8
  camera: ^0.9.4+12
  freezed: ^1.1.1
  flutter_cache_manager: ^3.3.0
  jiffy: ^5.0.0
  url_launcher: ^6.0.20
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_analytics: ^9.1.2
  flutter_login: ^3.2.0
  shared_preferences: ^2.0.13
  google_sign_in: ^5.2.4
  firebase_messaging: ^11.2.11

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: SignInOptions
      fonts:
        - asset: assets/SignInOptions.ttf

  uses-material-design: true
  generate: true
